import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://192.168.1.101:4200/');
  await page.getByRole('textbox', { name: 'SSO ID' }).click();
  await page.getByRole('textbox', { name: 'SSO ID' }).press('ControlOrMeta+V');
  await page.getByRole('textbox', { name: 'SSO ID' }).fill('789456123');
  await page.getByRole('textbox', { name: 'SSO ID' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter password' }).fill('mlive@12');
  await page.getByRole('textbox', { name: 'Enter password' }).press('Tab');
  await page.getByRole('button').filter({ hasText: /^$/ }).press('Tab');
  await page.getByRole('button', { name: '↻' }).press('Tab');
  await page.getByRole('textbox', { name: 'Please enter the CAPTCHA' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter the CAPTCHA' }).fill('MME3XR');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('button', { name: ' Masters ' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Booking Time' }).click();
  await page.getByRole('button', { name: 'Clear' }).click();
  await page.getByRole('textbox', { name: 'Start Time' }).click();
  await page.getByRole('textbox', { name: 'Start Time' }).fill('06:00');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Enter');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Enter');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Enter');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'End Time' }).click();
  await page.getByRole('textbox', { name: 'End Time' }).fill('20:00');
  await page.getByRole('textbox', { name: 'End Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'End Time' }).press('Enter');
  await page.getByRole('textbox', { name: 'End Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'End Time' }).press('Tab');
  await page.getByRole('textbox', { name: 'End Time' }).press('Enter');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Clear' }).click();
});