import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://192.168.1.101:4200/');
  await page.getByRole('textbox', { name: 'SSO ID' }).click();
  await page.getByRole('textbox', { name: 'SSO ID' }).press('ControlOrMeta+V');
  await page.getByRole('textbox', { name: 'SSO ID' }).click();
  await page.getByRole('textbox', { name: 'SSO ID' }).fill('789456123');
  await page.getByRole('textbox', { name: 'SSO ID' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter password' }).fill('mlive@12');
  await page.getByRole('textbox', { name: 'Enter password' }).press('Tab');
  await page.getByRole('button').filter({ hasText: /^$/ }).press('Tab');
  await page.getByRole('button', { name: '↻' }).press('Tab');
  await page.getByRole('textbox', { name: 'Please enter the CAPTCHA' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter the CAPTCHA' }).fill('GHS5GW');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('button', { name: ' Masters ' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Users' }).click();
  await page.getByRole('button', { name: 'Add User' }).click();
  await page.getByRole('textbox', { name: 'Enter Username' }).click();
  await page.getByRole('textbox', { name: 'Enter Username' }).fill('RO');
  await page.getByRole('textbox', { name: 'Enter Username' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter Username' }).fill('Rohit');
  await page.getByRole('textbox', { name: 'Enter Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter SSO ID' }).fill('001212187');
  await page.getByRole('textbox', { name: 'Enter SSO ID' }).press('Tab');
  await page.locator('form').getByRole('combobox').selectOption('buyer');
  await page.getByRole('textbox', { name: 'Enter Contact Number' }).click();
  await page.getByRole('textbox', { name: 'Enter Contact Number' }).fill('0254875120');
  await page.getByRole('textbox', { name: 'Enter Contact Number' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter Email ID' }).fill('rohit123@gmail.com');
  await page.getByRole('textbox', { name: 'Enter Email ID' }).press('Tab');
  await page.getByRole('combobox').nth(3).selectOption('Purchase');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
});