import { test, expect } from '@playwright/test';

test.setTimeout(600000);
test('test', async ({ page }) => {
  await page.goto('http://192.168.1.101:4200/');
  await page.getByRole('textbox', { name: 'SSO ID' }).click();
  await page.getByRole('textbox', { name: 'SSO ID' }).click();
  await page.getByRole('textbox', { name: 'SSO ID' }).press('ControlOrMeta+V');
  await page.getByRole('textbox', { name: 'SSO ID' }).fill('789456123');
  await page.getByRole('textbox', { name: 'SSO ID' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter password' }).fill('mlive@12');
  await page.getByRole('textbox', { name: 'Enter password' }).press('Tab');
  await page.getByRole('button').filter({ hasText: /^$/ }).press('Tab');
  await page.getByRole('button', { name: '↻' }).press('Tab');
  await page.getByRole('textbox', { name: 'Please enter the CAPTCHA' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter the CAPTCHA' }).fill('KJDD22');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('button', { name: ' Masters ' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Users' }).click();
  await page.getByRole('button', { name: ' Masters ' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Suppliers' }).click();
  await page.getByRole('button', { name: ' Masters ' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Escalation' }).click();
  await page.getByRole('button', { name: ' Masters ' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Holidays' }).click();
  await page.getByRole('button', { name: ' Masters ' }).click();
  await page.getByRole('list').getByText('Remarks').click();
  await page.getByRole('button', { name: ' Masters ' }).click();
  await page.getByRole('list').getByText('Modality').click();
  await page.getByRole('button', { name: ' Masters ' }).click();
  await page.getByRole('list').getByText('Booking Time').click();
  await expect(page.getByRole('button', { name: ' Masters ' })).toBeVisible();
  await page.getByRole('button', { name: ' Masters ' }).click();
  await page.getByRole('list').getByText('Lead Time').click();
  await page.getByRole('button', { name: ' Masters ' }).click();
  await page.getByRole('list').getByText('Role Base Access').click();
});