import { test, expect } from '@playwright/test';

test.setTimeout(600000);
test('test', async ({ page }) => {
  await page.goto('http://192.168.1.101:4200/');
  await page.getByRole('textbox', { name: 'SSO ID' }).click();
  await page.getByRole('textbox', { name: 'SSO ID' }).click();
  await page.getByRole('textbox', { name: 'SSO ID' }).fill('789456123');
  await page.getByRole('textbox', { name: 'SSO ID' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter password' }).fill('mlive@12');
  await page.getByRole('textbox', { name: 'Enter password' }).press('Tab');
  await page.getByRole('button').filter({ hasText: /^$/ }).press('Tab');
  await page.getByRole('button', { name: '↻' }).press('Tab');
  await page.getByRole('textbox', { name: 'Please enter the CAPTCHA' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter the CAPTCHA' }).fill('YCT567');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('button', { name: ' Masters ' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Escalation' }).click();
  await page.getByRole('button', { name: 'Add Escalation' }).click();
  await page.getByRole('combobox').selectOption('2');
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('NARESH');
  await page.getByRole('textbox', { name: 'Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Phone' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Phone' }).fill('9494415722');
  await page.getByRole('textbox', { name: 'Phone' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email' }).fill('nareshlesnar11288@gmail.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByPlaceholder('Delay (hours)').fill('');
  await page.getByPlaceholder('Delay (hours)').press('ArrowUp');
  await page.getByPlaceholder('Delay (hours)').fill('1');
  await page.getByPlaceholder('Delay (hours)').press('ArrowUp');
  await page.getByPlaceholder('Delay (hours)').fill('2');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Edit' }).first().click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.locator('.slider').first().click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('.slider').first().click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Buyer Escalation' }).click();
  await page.getByRole('button', { name: 'Edit' }).first().click();
  await page.getByRole('combobox').selectOption('6');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.locator('.slider').first().click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('.slider').first().click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Add Escalation' }).click();
  await page.getByRole('combobox').selectOption('5');
  await page.locator('div').filter({ hasText: /^Escalation Time Out\(Hours\) :$/ }).click();
  await page.getByPlaceholder('Enter Escalation Time Out').fill('1');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'General Escalation' }).click();
});