import { test, expect } from '@playwright/test';

test.setTimeout(6000000);
test('test', async ({ page }) => {
  await page.goto('http://192.168.1.101:4200/');
  await page.getByRole('textbox', { name: 'SSO ID' }).click();
  await page.getByRole('textbox', { name: 'SSO ID' }).fill('789456123');
  await page.getByRole('textbox', { name: 'SSO ID' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter password' }).fill('mlive@12');
  await page.getByRole('textbox', { name: 'Enter password' }).press('Tab');
  await page.getByRole('button').filter({ hasText: /^$/ }).press('Tab');
  await page.getByRole('button', { name: '↻' }).press('Tab');
  await page.getByRole('textbox', { name: 'Please enter the CAPTCHA' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please enter the CAPTCHA' }).fill('WN5TTQ');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('button', { name: ' Masters ' }).click();
  await page.getByRole('list').getByText('Remarks').click();
  await page.getByRole('textbox', { name: 'Search Remarks...' }).click();
  await page.getByRole('textbox', { name: 'Search Remarks...' }).fill('');
  await page.getByRole('combobox').nth(1).selectOption('2');
  await page.getByRole('combobox').nth(1).selectOption('4');
  await page.getByRole('combobox').nth(1).selectOption('3');
  await page.getByRole('combobox').nth(1).selectOption('2');
  await page.getByRole('combobox').nth(1).selectOption('6');
  await page.getByText('Refresh').click();
  await page.getByRole('combobox').nth(1).selectOption('1');
  await page.locator('div').filter({ hasText: /^Refresh$/ }).click();
  await page.getByRole('combobox').nth(1).selectOption('3');
  await page.locator('div').filter({ hasText: /^Refresh$/ }).click();
  await page.getByRole('combobox').first().selectOption('25');
  await page.getByRole('combobox').first().selectOption('50');
  await page.getByRole('button', { name: 'Add Remarks' }).click();
  await page.locator('form').getByRole('combobox').selectOption('BIN');
  await page.getByRole('textbox', { name: 'Enter Remarks Name' }).click();
  await page.getByRole('textbox', { name: 'Enter Remarks Name' }).fill('TEST');
  await page.getByRole('textbox', { name: 'Enter Remarks Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter Remarks Name' }).fill('Testing');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('combobox').first().selectOption('100');
  await page.getByRole('button', { name: '1' }).click();
});